name: Continuos Integration

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
      
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.35.0

      - name: Check linting of Terraform files
        id: lint
        run: tflint

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Install TFSec
        run: |
          curl -L https://github.com/tfsec/tfsec/releases/download/v1.15.2/tfsec-linux-amd64 -o tfsec && \
          sudo chmod +x tfsec && \
          sudo mv tfsec /usr/local/bin/tfsec

      - name: TFSec
        id: sec
        run: tfsec

  documentation:
    needs: continuous-integration
    name: Documentation
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.1.7
      
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: "github-actions"
          git-push-user-email: "github-actions@github.com"
          git-commit-message: "docs(terraform): generated terraform docs [skip ci]"
